### ISSUE TITLE
Why is yiisoft/yii-app required?

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii-app-template#1]
continued from https://github.com/yiisoft/yii-app/issues/40#issuecomment-414712463

Why is `yiisoft/yii-app` required here https://github.com/yiisoft/yii-app-template/blob/master/composer.json#L60? 
It's another application in this application template. Should this be `yiisoft/core`?

**Comment by hiqsol** [comment]
Just see the list of files in this repository:

```
.docker/nginx/etc/nginx/conf.d/vhost.conf
.env.dist
.gitignore
.scrutinizer.yml
.travis.yml
LICENSE
README.md
composer.json
config/common.php
config/params.php
config/web.php
docker-compose.yml
hidev.yml
public/assets/.gitignore
public/favicon.ico
public/index.php
runtime/.gitignore
```

As you can see there is no PHP classes in this repository. 
The actual application implementation is in the `yii-app` repository.
And this repository is like a thin wrapper around `yii-app` and contains only files needed to this particular installation of the application: configuration and files needed for deploy.

I call this approach application nesting. It allows to inherit and extend application like you do it with classes.

**Comment by schmunk42** [comment]
> I call this approach application nesting. It allows to inherit and extend application like you do it with classes.

But shouldn't this be done with modules? You get a lot of extra (unneeded) files when nesting applications.

**Comment by hiqsol** [comment]
Which files you think unneeded?

**Comment by schmunk42** [comment]
From here: https://github.com/yiisoft/yii-app
- `bin`
- `public`
- all *files* in the project root
- `config` overlaps with other applications config

**Comment by hiqsol** [comment]
- Removed `bin`. The `yii` script is in `yii-console` now.
- Removed files from `public`, those files are in `yii-app-template` now. Left only css files there, they are used in asset bundle.
- Files in the project root are packaging files (like letter envelope). When we split packages we have packaging files, we cannot do anything with it.
- Configs are intended to overlap. composer-config-plugin ensures configs are merged in proper order. So we can define default configuration in 'inner' packages and gradually tune it in 'outer' packages. The `yii-app-template` is a template for the outermost package so it can redefine anything.
